# Generated by Django 4.0.6 on 2022-07-28 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_alter_schedule_schedule_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='seats',
            new_name='seat_capacity',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_taken',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='position',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base_app.seat'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 17, 26, 31, 954466)),
        ),
    ]
