# Generated by Django 4.0.6 on 2022-08-02 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_reservation_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 13, 7, 28, 568499)),
        ),
    ]
