# Generated by Django 4.0.6 on 2022-08-09 15:03

import base_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0020_alter_movie_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateTimeField(default=base_app.utils.today),
        ),
    ]
