# Generated by Django 4.1 on 2022-08-25 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0023_seat_is_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='schedules', to='base_app.movie'),
        ),
    ]
