# Generated by Django 4.0.6 on 2022-07-21 13:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('description', models.TextField(default=None, max_length=200)),
                ('city', models.CharField(default=None, max_length=100)),
                ('address', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(default=None, max_length=100)),
                ('phone', models.CharField(default=None, max_length=20)),
                ('cinema', models.CharField(default=None, max_length=50)),
                ('subject', models.CharField(default=None, max_length=30)),
                ('message', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('description', models.TextField(default=None, max_length=400)),
                ('seats', models.IntegerField(default=0)),
                ('cinema', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='base_app.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('poster', models.ImageField(default=None, upload_to='static/media/')),
                ('description', models.TextField(default=None)),
                ('year', models.IntegerField(default=None)),
                ('director', models.CharField(default=None, max_length=200)),
                ('imdb_link', models.CharField(default='https://imdb.com', max_length=400)),
                ('imdb_id', models.IntegerField(default=None)),
                ('url', models.CharField(default=None, max_length=400)),
                ('duration', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_taken', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=None)),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.DateTimeField(default=datetime.datetime(2022, 7, 21, 16, 51, 1, 390230))),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.hall')),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='base_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base_app.schedule')),
                ('seat', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='base_app.seat')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
