# Generated by Django 4.0.6 on 2022-07-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_link',
            field=models.CharField(default='https://imdb.com', max_length=400),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.CharField(default='', max_length=400),
        ),
    ]
