# Generated by Django 4.0.6 on 2022-07-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_remove_movie_imdb_movie_director_movie_imdb_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
