# Generated by Django 4.0.6 on 2022-07-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_movie_description_alter_movie_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('description', models.TextField(default=None, max_length=400)),
                ('seats', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.hall'),
        ),
    ]
