# Generated by Django 4.0.6 on 2022-07-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_contactmessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('description', models.TextField(default=None, max_length=200)),
                ('city', models.CharField(default=None, max_length=100)),
                ('address', models.TextField(default=None)),
                ('hall', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
