# Generated by Django 4.0.6 on 2022-07-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_cinema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='base_app.movie')),
            ],
        ),
    ]
