# Generated by Django 4.0.6 on 2022-07-28 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_rename_seats_hall_seat_capacity_remove_seat_is_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 17, 35, 0, 562877)),
        ),
    ]
