# Generated by Django 4.0.6 on 2022-07-13 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 9, 38, 43, 537377)),
        ),
    ]
