# Generated by Django 4.0.6 on 2022-07-29 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_alter_schedule_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='name',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 9, 40, 23, 331015)),
        ),
    ]
