# Generated by Django 4.0.6 on 2022-07-13 08:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_remove_schedule_name_alter_schedule_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='hall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='base_app.hall'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 11, 16, 12, 705183)),
        ),
    ]
