# Generated by Django 4.0.6 on 2022-07-15 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_schedule_hall_alter_schedule_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default=None, upload_to='static/media/'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 16, 59, 9, 145957)),
        ),
    ]
