# Generated by Django 4.0.6 on 2022-07-29 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_seat_name_alter_schedule_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 10, 23, 28, 954556)),
        ),
        migrations.AlterField(
            model_name='seat',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
