# Generated by Django 4.0.6 on 2022-07-21 07:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_reservation_alter_schedule_schedule_time_seat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='hall',
        ),
        migrations.AlterField(
            model_name='cinema',
            name='hall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base_app.hall'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 10, 26, 41, 491201)),
        ),
    ]
