# Generated by Django 4.0.6 on 2022-07-21 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_remove_movie_hall_alter_cinema_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 10, 27, 7, 510234)),
        ),
    ]
