# Generated by Django 4.0.6 on 2022-07-21 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_alter_schedule_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 15, 54, 35, 720869)),
        ),
    ]
