# Generated by Django 4.0.6 on 2022-08-03 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_alter_schedule_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_id',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 12, 32, 41, 743680)),
        ),
    ]
