# Generated by Django 4.0.6 on 2022-08-04 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0016_movie_trailer_id_alter_schedule_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 1, 1, 1, 1)),
        ),
    ]
